### ISSUE TITLE
linear_polymer() method returns OpenBabel Molecule instead of RDKit Mol object

### ISSUE THREAD

**Issue by aliheh** [alejandrosantanabonilla/pysoftk#9]
linear_polymer() method in LP class, returns OpenBabel Molecule instead of RDKit Mol object as written in the method docstring.

The problem is the  _ff_ob_relaxation()_ function in _tools/utils_ob.py_ returns OpenBabel Molecule.

is there any way we can fix it? to get RDKit Mol object.

There is _rmgpy_ package which has the capabilities to convert mol objects between RDKit and OpenBabel; however, isn't there a simpler method for conversion between these two?

**Comment by alejandrosantanabonilla** [comment]
Hello, thanks for contacting me and using pysoftk. Thanks for looking into the docstrings and I am going to change that. So, we have decided that we are not returning RDkit object methods anymore for Lp since the Embedded method from RDkit is very unreliable for long molecules. Therefore, we have decided to use pybel instead whose implementation of embedding is much more robust. I am not going to change this feature since many polymers are going to fail due to the Embedding method limitations in RDKit.

However, there are couple of ways that you can recover the molecule as an RDKit method. I am attaching the following 
script that shows you three different ways of recovering the RDKit object. The most important part is the 

**from openbabel import pybel as pb** 

which gives you access to all the openbabel methods. This is already installed in your PC since pysoftk needs it.

I hope this helps.

Cheers,
Alejandro

**Code sample:**

from pysoftk.linear_polymer.super_monomer import *
from pysoftk.linear_polymer.linear_polymer import *
from pysoftk.format_printers.format_mol import *

from openbabel import pybel as pb 

#Initial molecule
monomer=Chem.MolFromSmiles('OC[C@@H]1O[C@@H](O[C@@H]2[C@H]3CO[C@@H]2[C@H](O)[C@H](Br)O3)[C@@H](O)[C@H](O)[C@@H]1OBr')
mh = Chem.AddHs(monomer)
AllChem.EmbedMolecule(mh)

#option1 using pybel 
gnew=Chem.MolFromSmiles(new.write("smi"))
print (gnew)

#option 2 to printing to mol using pysoftk and then re-reading for RDKit
Fmt(new).mol_print("pol.mol")
g_new_1=Chem.MolFromMolFile("pol.mol")
print (g_new_1)

#option 2 using pybel to print and re read as RDkit object
new.write("mol", f"polymer_{n_monomers}.mol")
g_new_2=Chem.MolFromMolFile("polymer_2.mol")
print (g_new_2)

**Comment by aliheh** [comment]
Hi, @alejandrosantanabonilla. Thank you for your thorough response and snippets.
